2020-03-26 09:09:15,990 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-26 09:09:15,992 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-26 09:09:15,996 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-26 09:09:15,997 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-26 09:09:15,997 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=2b36bc16-7c4c-4ff4-b849-18b9d0a2ae25
- device_id=android-d13a49bfddbe7ce7
2020-03-26 09:09:15,997 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-26 09:09:28,433 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [400]>
2020-03-26 09:09:28,433 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/timeline/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:09:28,434 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:09:28,434 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:09:28,435 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:08,897 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [400]>
2020-03-26 09:10:08,898 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_tray/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:08,898 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:08,898 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:08,898 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:11,442 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/ranked_recipients/ returned response: <Response [400]>
2020-03-26 09:10:11,443 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/ranked_recipients/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:11,443 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:11,444 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:11,444 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:13,931 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-26 09:10:13,931 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-26 09:10:13,932 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-26 09:10:13,933 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-26 09:10:13,934 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/nurchuliss_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=d2ae494d-2f06-4681-a48b-9c921cf0c11b
- uuid=423e6931-be2b-4a9b-9c1b-4d8fe19b14e6
- client_session_id=1e77beb9-13b1-4e6b-a0fb-c8412f093735
- device_id=android-19c11c9b12e66074
2020-03-26 09:10:13,934 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-26 09:10:15,390 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/ranked_recipients/ returned response: <Response [400]>
2020-03-26 09:10:15,391 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/ranked_recipients/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:15,391 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:15,392 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:15,392 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:18,662 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/inbox/ returned response: <Response [400]>
2020-03-26 09:10:18,662 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/inbox/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:18,662 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:18,663 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:18,663 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:19,620 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
2020-03-26 09:10:29,419 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: direct_v2/get_presence/ returned response: <Response [400]>
2020-03-26 09:10:29,419 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/get_presence/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:29,419 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:29,421 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:29,421 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:30,484 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [400]>
2020-03-26 09:10:30,484 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/news/inbox/%253Flimited_activity%253Dtrue%2526show_su%253Dtrue", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:30,484 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:30,486 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:30,486 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:30,878 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
2020-03-26 09:10:32,281 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: users/profile_notice/ returned response: <Response [400]>
2020-03-26 09:10:32,281 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/users/profile_notice/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:32,281 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:32,282 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:32,282 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:32,286 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/ranked_recipients/ returned response: <Response [200]>
2020-03-26 09:10:37,375 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: discover/explore/ returned response: <Response [400]>
2020-03-26 09:10:37,375 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/discover/explore/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:37,375 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:37,377 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:37,377 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:37,378 - instabot version: 0.115.0 (api) - INFO - Login flow failed, the cookie is broken. Relogin again.
2020-03-26 09:10:37,379 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-26 09:10:37,379 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-26 09:10:37,380 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=fa549058-412a-463b-8d79-e5410f05e77f
- device_id=android-d13a49bfddbe7ce7
2020-03-26 09:10:37,380 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-26 09:10:40,200 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/ranked_recipients/ returned response: <Response [200]>
2020-03-26 09:10:40,629 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/inbox/ returned response: <Response [200]>
2020-03-26 09:10:42,900 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: direct_v2/get_presence/ returned response: <Response [200]>
2020-03-26 09:10:45,569 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
2020-03-26 09:10:45,606 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2020-03-26 09:10:45,607 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/get_prefill_candidates/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:45,607 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:45,611 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:45,611 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:46,119 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: users/profile_notice/ returned response: <Response [200]>
2020-03-26 09:10:46,223 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [400]>
2020-03-26 09:10:46,223 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/qe/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:46,224 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:46,226 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:46,228 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:48,784 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [400]>
2020-03-26 09:10:48,785 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/launcher/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:48,785 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:48,786 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:48,786 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:49,256 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [400]>
2020-03-26 09:10:49,256 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/contact_point_prefill/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:49,256 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:49,260 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:49,260 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:49,612 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-26 09:10:49,613 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/login/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-26 09:10:49,613 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:10:49,613 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-26 09:10:49,614 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-26 09:10:49,614 - instabot version: 0.115.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-26 09:10:49,615 - instabot version: 0.115.0 (api) - INFO - Username or password is incorrect.
2020-03-26 09:10:50,415 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: discover/explore/ returned response: <Response [200]>
2020-03-26 09:10:50,423 - instabot version: 0.115.0 (api) - INFO - Logged-in successfully as 'nurchuliss'!
2020-03-26 09:10:50,424 - instabot version: 0.115.0 (bot_checkpoint) - DEBUG - Loading Checkpoint file from: /var/www/html/example.com/public_html/cron/insta/config/nurchuliss.checkpoint
2020-03-26 09:11:25,050 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-26 09:11:25,052 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-26 09:11:25,053 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-26 09:11:26,862 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-03-26 09:11:27,673 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-03-26 09:11:29,279 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-03-26 09:11:29,591 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-03-26 09:11:31,780 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-26 09:11:31,781 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "The username you entered doesn't appear to belong to an account. Please check your username and try again.", "invalid_credentials": true, "error_title": "Incorrect Username", "buttons": [{"title": "Try Again", "action": "dismiss"}], "status": "fail", "error_type": "invalid_user"}
2020-03-26 09:11:31,781 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-26 09:11:31,783 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: The username you entered doesn't appear to belong to an account. Please check your username and try again.
2020-03-26 09:11:31,785 - instabot version: 0.115.0 (api) - INFO - Logged-in successfully as 'nur_chuliss'!
2020-03-26 09:11:31,786 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: True
2020-03-26 09:11:31,789 - instabot version: 0.115.0 (api_login) - ERROR - Exception raised: 'ds_user_id'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api_login.py", line 144, in login_flow
    check_flow.append(self.sync_device_features())
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 382, in sync_device_features
    data["_uid"] = self.user_id
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 636, in user_id
    return self.cookie_dict["ds_user_id"]
KeyError: 'ds_user_id'

2020-03-26 09:11:31,789 - instabot version: 0.115.0 (bot_checkpoint) - DEBUG - Loading Checkpoint file from: /var/www/html/example.com/public_html/cron/insta/config/nur_chuliss.checkpoint
2020-03-26 09:11:59,726 - instabot version: 0.115.0 (bot_checkpoint) - DEBUG - Saving Checkpoint file to: /var/www/html/example.com/public_html/cron/insta/config/nur_chuliss.checkpoint
2020-03-26 09:11:59,728 - instabot version: 0.115.0 (bot) - INFO - Total requests: 5
2020-03-26 09:11:59,730 - instabot version: 0.115.0 (bot_checkpoint) - DEBUG - Saving Checkpoint file to: /var/www/html/example.com/public_html/cron/insta/config/nurchuliss.checkpoint
2020-03-26 09:11:59,732 - instabot version: 0.115.0 (bot) - INFO - Total requests: 162
